---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: local-application
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: kobo
            repoURL: https://gitlab.com/api/v4/projects/32216873/packages/helm/stable
            chart: kobo
            namespace: tools

          - name: pgbouncer
            repoURL: https://github.com/one-acre-fund/oaf-public-charts.git
            path: charts/pgbouncer
            namespace: database

          - name: pgadmin
            repoURL: https://github.com/orchide/pgAdminChart.git
            path: .
            namespace: database

  template:
    metadata:
      name: "{{name}}-poc"
    spec:
      project: default
      source:
        repoURL: "{{repoURL}}"
        targetRevision: main
        path: "{{path}}"
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
