---
apiVersion: v1
kind: Secret
metadata:
  name: oaf-public-charts
  namespace: argocd
  annotations:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/one-acre-fund/oaf-public-charts.git
  type: git

---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-chart
  namespace: argocd
  annotations:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/orchide/pgAdminChart.git
  type: git

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: local-application
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: kobo
            repoURL: https://github.com/one-acre-fund/oaf-public-charts.git
            chart: kobo
            path: charts/kobo
            namespace: tools
          - name: pgbouncer
            repoURL: https://github.com/one-acre-fund/oaf-public-charts.git
            chart: pgbouncer
            path: charts/pgbouncer
            namespace: database
          - name: pgadmin
            repoURL: https://github.com/orchide/pgAdminChart.git
            chart: pgadmin
            path: charts/pgadmin
            namespace: database
  template:
    metadata:
      name: "{{name}}-poc"
    spec:
      project: default
      source:
        repoURL: "{{repoURL}}"
        targetRevision: main
        chart: "{{chart}}"
        path: "{{path}}"
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
