apiVersion: v1
kind: Secret
metadata:
  name: oaf-public-charts-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://gitlab.com/api/v4/projects/32216873/packages/helm/stable
  type: helm
  name: oaf-public-charts-helm
