apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-chart
  namespace: argocd
  annotations:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/orchide/pgAdminChart.git
  type: git
